"""Record every phrase the game says with a natural neural voice, one clip per phrase.

  python3 -m venv .venv && .venv/bin/pip install edge-tts
  .venv/bin/python tools/make_voice.py

The phrases come from src/voice/phrases.ts (read through tools/phrases.ts). Each clip is written to
public/voice/<id>.mp3, and src/voice/voice.gen.ts maps every phrase to its file. Only phrases without a
clip are recorded; clips no longer in the list are deleted. The build fails if any phrase lacks a clip.
"""
import asyncio, hashlib, json, re, subprocess
from pathlib import Path
import edge_tts

VOICE = 'en-US-AvaNeural'
RATE = '-8%'
ROOT = Path(__file__).resolve().parent.parent
CLIPS = ROOT / 'public' / 'voice'
INDEX = ROOT / 'src' / 'voice' / 'voice.gen.ts'


def speakable(s):
    for a, b in [('$1 Bill', 'one dollar bill'), ('$5 Bill', 'five dollar bill'), ('$1', 'one dollar'), ('$5', 'five dollars'),
                 ('VROOM', 'Vroom'), ('Truck-tastic', 'Truck tastic')]:
        s = s.replace(a, b)
    return re.sub(r'(\d+)¢', lambda m: 'one cent' if m[1] == '1' else f'{m[1]} cents', s)


def clip_id(text):
    # a change of voice, rate or spoken text makes a new clip
    return hashlib.sha1(f'{VOICE}|{RATE}|{speakable(text)}'.encode()).hexdigest()[:12]


async def record(text, out, sem):
    async with sem:
        for attempt in range(3):
            try:
                return await edge_tts.Communicate(speakable(text), VOICE, rate=RATE).save(str(out))
            except Exception:
                if attempt == 2:
                    raise
                await asyncio.sleep(2)


async def main():
    phrases = json.loads(subprocess.run(['npx', 'tsx', 'tools/phrases.ts'], cwd=ROOT, check=True, capture_output=True, text=True).stdout)
    CLIPS.mkdir(parents=True, exist_ok=True)
    files = {p: f'{clip_id(p)}.mp3' for p in phrases}
    todo = [p for p, f in files.items() if not (CLIPS / f).exists()]
    sem = asyncio.Semaphore(8)
    await asyncio.gather(*(record(p, CLIPS / files[p], sem) for p in todo))
    keep = set(files.values())
    stale = [f for f in CLIPS.glob('*.mp3') if f.name not in keep]
    for f in stale:
        f.unlink()
    body = ''.join(f'  {json.dumps(p, ensure_ascii=False)}: {json.dumps(f)},\n' for p, f in files.items())
    INDEX.write_text('// Generated by tools/make_voice.py. Do not edit: every phrase in phrases.ts and its clip in public/voice/.\n'
                     f'export const CLIPS: Record<string, string> = {{\n{body}}};\n')
    print(f'{len(phrases)} phrases: recorded {len(todo)}, removed {len(stale)} stale clips, with {VOICE}')

asyncio.run(main())
